### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by elleyer** [elleyerium/Elysium-Web#1]
### TODO LIST FOR ELYSIUM-WEB
PHP ---> Laravel
### Main
   - [ ] Download client Types
     - [ ] Links to Google Play | App store / APK-file
     - [ ] Download client for windows function
   - [ ] auth action
      - [ ] Register
        - [ ] Check if account exists
      - [ ] Login
        - [ ] verification
      - [ ] Sync user data between server and web (same log/pass)
   - [ ] Player profile
     - [ ] Statistics for player profile wall/status
       - [ ] Scores
       - [ ] Level
       - [ ] SpacePoints
     - [ ] Game-type statistics
     - [ ] Avatar selector
       - [ ] Max h*w
       - [ ] Max size
     - [ ] Currently player status
       - [ ] Online/In-game
     - [ ] All other data about player like "last seen", etc. (more a bit later)
     - [ ] Comments
       - [ ] User profile comments
   - [ ] Leaderboards
     - [ ] Sort by game-types
     - [ ] TOP-100
     - [ ] Click on player profile from Leaderboard
     - [ ] Depended by SP count (SpacePoints)
   - [ ] Events
     - [ ] Events and news from main Server
     - [ ] Sync events between web and client
     - [ ] Game updates, dev-log
   - [ ] MP data
     - [ ] Currently players count
     - [ ] lobby list
       - [ ] room type (players count, game-type, minimum level)
     - [ ] available players
     - [ ] friends listing
       - [ ] incoming requests
       - [ ] online friends
       - [ ] friend status
   - [ ] Workshop
     - [ ] own spaceships
     - [ ] own maps (backgrounds)
     - [ ] own weapon-types
     - [ ] moderation fuctions
   - [ ] Documentation
     - [ ] "How to play"
     - [ ] Web doc
     - [ ] Web preferences (more a bit later)
### Settings
   - [ ] Web settings
     - [ ] Language settings
     - [ ] Log out 
     - [ ] Private data list
       - [ ] Change password action
       - [ ] Change E-mail action

**Comment by b1oki** [comment]
вот тут надо было в виде карточек раскидать https://github.com/elleyerium/Elysium-Web/projects
а карточкой может быть issue

**Comment by elleyer** [comment]
Да, позже перенесу, спасибо!
